version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skarpa-bytom-app
    restart: unless-stopped

    env_file: .env

    volumes:
      - skarpa_data:/app/data

    expose:
      - "3000"

    networks:
      - skarpa-network

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'


    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  skarpa-network:
    driver: bridge
    external: true

volumes:
  skarpa_data:
    driver: local
    name: skarpa_sqlite_data
